import os
import streamlit as st
from PIL import Image

def image_gallery():
    st.header("Generated Images")
    st.write("View images generated by the GANs from generation script.")

    # Controls
    col1, col2 = st.columns(2)
    with col1:
        model = st.selectbox("Model", ["wgan_gp", "dcgan", "progan"])

    with col2:
        size = st.selectbox("Image Size", [64, 128])

    folder = f"output/{model}_{size}"
    image_files = sorted([
        os.path.join(folder, f)
        for f in os.listdir(folder)
        if f.endswith(".png")
    ])

    if not image_files:
        st.warning("No images found.")
        return

    cols_per_row = 5
    rows = [image_files[i:i+cols_per_row] for i in range(0, len(image_files), cols_per_row)]
    for row in rows:
        cols = st.columns(len(row))
        for col, img_path in zip(cols, row):
            col.image(Image.open(img_path), caption=os.path.basename(img_path), use_container_width=True)